### ISSUE TITLE
To get wildcard ip from github

### ISSUE THREAD

**Issue by HORKimhab** [lord-alfred/ipranges#12]
To refactor `3.217.79.163/32` to `3.217.*`
Python code: 

import requests
import ipaddress

""" 
  Convert ip
  "3.217.79.163/32",
  "3.217.93.44/32",
  
  -> "3.127.*"  
"""

url = "https://raw.githubusercontent.com/lord-alfred/ipranges/main/github/ipv4.txt"

response = requests.get(url)
ip_ranges = response.text.strip().split("\n")

def convert_to_wildcard(ip_ranges):
    wildcard_ranges = set()
    for ip_range in ip_ranges:
        network = ipaddress.ip_network(ip_range, strict=False)
        wildcard = f"{network.network_address.exploded.split('.')[0]}.{network.network_address.exploded.split('.')[1]}.*"
        wildcard_ranges.add(wildcard)
    return sorted(wildcard_ranges)

wildcard_ranges = convert_to_wildcard(ip_ranges)
for wildcard in wildcard_ranges:
    print(wildcard)

**Comment by lord-alfred** [comment]
I think its not need and have errors in code
