### ISSUE TITLE
Microsoft data only includes Azure ranges

### ISSUE THREAD

**Issue by fschucht** [lord-alfred/ipranges#9]
First of all, thanks for putting together this great repo @lord-alfred!

We are using the datasets to disable some features for bots. Recently, we started getting lots of traffic from some Outlook bots. However, their IP ranges are not included in the data of this repo. The reason seems to be that the repo only includes the Azure ip ranges and not the full list of all Microsoft ip ranges.

Microsoft publishes all public ips, including the Outlook ones, here: https://www.microsoft.com/en-us/download/details.aspx?id=53602

I am happy to contribute a fix in a pr but would like to get some input first on the implementation. Should this be added to the existing Microsoft dataset or should it be added as a new separated one?

**Comment by lord-alfred** [comment]
Thanks for that comment, it's very helpful!
Actually already now MS addresses include not only Azure and you can add the designated addresses from here as well.

I will be glad if you bring Pull Request, in it I expect:
- Rename function`download_and_parse` to `download_and_parse_json`: https://github.com/lord-alfred/ipranges/blob/main/microsoft/downloader.sh#L12
- Add a new function `download_and_parse_csv` to handle new kind of lists
- Add a new function call:  https://github.com/lord-alfred/ipranges/blob/main/microsoft/downloader.sh#L32
- Test that this script works
- Remove Azure references from the readme: https://github.com/lord-alfred/ipranges/blob/main/README.md

Thank you very much!

**Comment by fschucht** [comment]
Thanks for the input! I submitted a pull request with the changes you outlined.
